[package]
name = "site-blocker"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.4.18", features = ["derive"] }
directories = "5.0.1"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
