---
name: Test

on:  # yamllint disable-line rule:truthy
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions: 
  contents: read
  # To report GitHub Actions status checks
  statuses: write

jobs:
  build:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup
        uses: dtolnay/rust-toolchain@stable

      - name: Cargo test
        run: cargo test --no-fail-fast --all-features

